### ISSUE TITLE
Setup Failed (Requirements for lamarzocco not found: ['lmcloud==4.0.2b2'])

### ISSUE THREAD

**Issue by mekenthompson** [zweckj/lamarzocco#16] opened 2023-10-28 05:05 UTC
Just started getting the below error message, I did update gateway version, not sure if related or not though.

Machine: Linea Mini
Gateway: v3.2-RC9
Firmware: 2.12

```
Logger: homeassistant.setup
Source: setup.py:185
First occurred: 15:57:32 (1 occurrences)
Last logged: 15:57:32

Setup failed for custom integration lamarzocco: Requirements for lamarzocco not found: ['lmcloud==4.0.2b2'].
```

**Comment by robinbohnen** [comment] 2023-10-28 09:00
Duplicate of https://github.com/zweckj/lamarzocco/issues/14

**Comment by zweckj** [comment] 2023-10-28 12:27
yep, duplicate of #14

**Closed by zweckj** 2023-10-28 12:27 UTC
